export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCES";
export const PURCHASE_FAILED = "PURCHASE_FAILED";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_START_SUCCESS";
export const AUTH__FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";